image: python:3.6-alpine

stages:
  - build
  - test

requirements:
  stage: build
  script:
    - pip install -r requirements.txt

unit_test:
  stage: test
  script:
    - python -m unittest discover -v
